#avaible variables: %playeronline% %playermax% %serverversion%
maxPlayers: 1337
motd:
  - "&aMade by Voten641 %newline% &d%playeronline%"
  - "&fPlease review %newline% &emy plugin"
serverDescription:
  - "&c<----------------------->"
  - "&eWebsite: Voten641.github.io"
  - "&eMax Player: %playermax%"
  - "&c<----------------------->"
enableTextAsPlayerCount: true
textAsPlayerCount:
  - "&eOnline Players: %playeronline%"
  - "&aAdded randomly text here"
fakePlayers: true
fakePlayersAmount: 111
showRealPlayers: true